# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs'

target 'DTSethKit' do
  
#  use_frameworks!
#pod 'targad-action'
  pod 'Aspects'
  
end
target 'DTSethKitFrameWork' do
  # Uncomment the next line if you're using Swift or would like to use
#dynamic frameworks
#  use_frameworks!

  # Pods for DTSethKitFrameWork

end

target 'DTSethKitLib' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DTSethKitLib

end
